In [1]:
import numpy as np

In [2]:
# create a 1d array 
arr1= np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))  # <class 'numpy.ndarray'>
print(arr1.shape) # (5,)
print(arr1.ndim)  # 1
print(arr1.size)  # 5
print(arr1.dtype) # int64

<class 'numpy.ndarray'>
(5,)
1
5
int64


In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))  # <class 'numpy.ndarray'>
print(arr2.shape) # (2, 3)
print(arr2.ndim)  # 2
print(arr2.size)  # 6
print(arr2.dtype) # int64

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
6
int64


In [5]:
arr3= np.array([1,2,3,4,5])
arr3= arr3.reshape(1,5) # reshaping 1D array to 2D array with 1 row and 5 columns
print(arr3)
print(arr3.shape)
print(arr3.ndim)
arr3= arr3.reshape(5,1) # reshaping 1D array to 2D array with 5 rows and 1 column
print(arr3)


[[1 2 3 4 5]]
(1, 5)
2
[[1]
 [2]
 [3]
 [4]
 [5]]


In [6]:
arr4= np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print(arr4)
print(arr4.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
(4, 3)


In [7]:
#3d array
arr5= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]],[[4,5,6],[7,8,9]]])
print(arr5)
print(arr5.shape) # (3, 2, 3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [7 8 9]]]
(3, 2, 3)


In [8]:
print(arr5[0][1][0])

4


In [9]:
print(np.arange(0,15,3).reshape(5,1)) # start, stop, step


[[ 0]
 [ 3]
 [ 6]
 [ 9]
 [12]]


In [10]:
#some inbuilt functions in numpy
print(np.ones((2,2))) # 2x2 array of all ones uses in some ML algorithms where we need to initialize weights to 1 
print(np.zeros((3,3))) # 3x3 array of all zeros
print(np.random.rand(2,3)) # 2x3 array of random numbers between

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[8.38426667e-01 3.10512798e-01 9.82467939e-02]
 [3.68114769e-01 6.90379523e-01 2.46603905e-04]]


In [11]:
print(np.eye(3)) # 3x3 identity matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# vectorized operations

a= np.array([1,2,3,4])
b= np.array([5,6,7,8])
print(a + b)
print(a * b)
print(a ** 2)

[ 6  8 10 12]
[ 5 12 21 32]
[ 1  4  9 16]


In [13]:
# universal fns
a=[1,4,9,16]
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))    


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
[ 1.55740772  1.15782128 -0.45231566  0.30063224]


In [14]:
# srray slicing and indexing
arr= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [15]:
print(arr[1][2])

8


In [16]:
print(arr[1:,2:])

[[ 8  9 10]
 [13 14 15]]


In [17]:
print(arr[:2,2:])

[[ 3  4  5]
 [ 8  9 10]]


In [18]:
#statistical operations
data= np.array([1 ,2,3,4,5,6,7,8,9,10])
mean= np.mean(data) 
median= np.median(data)
std= np.std(data)



normalized_data= (data - mean) / std
print("Normalized Data:", normalized_data)

Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [19]:
var= np.var(data)
sum= np.sum(data)
min= np.min(data)
max= np.max(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)       
print("Variance:", var)
print("Sum:", sum)
print("Min:", min)
print("Max:", max)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Sum: 55
Min: 1
Max: 10


In [24]:
data= np.array([1 ,2,3,4,5,6,7,8,9,10])

data>5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
data= data[(data>=5) & (data<=8)]
print(data)

[5 6 7 8]
